name: Publish @fidera/loopback-rabbitmq to GitHub Packages

on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@fidera"
      - run: npm install
      - run: npm run build
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
